//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Epic.Training.Project.Inventory.Text {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Epic.Training.Project.Inventory.Text.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is acceptable. Press [ENTER] to confirm or any other key to discard the change.
        /// </summary>
        internal static string CONFIRM_PROMPT {
            get {
                return ResourceManager.GetString("CONFIRM_PROMPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;&lt;ITEM CREATION&gt;&gt;.
        /// </summary>
        internal static string CREATE_ITEM {
            get {
                return ResourceManager.GetString("CREATE_ITEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EpicInventory.
        /// </summary>
        internal static string DefaultBinDir {
            get {
                return ResourceManager.GetString("DefaultBinDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to localappdata.
        /// </summary>
        internal static string DefaultBinDirEnv {
            get {
                return ResourceManager.GetString("DefaultBinDirEnv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;&lt;ITEM EDITOR&gt;&gt;.
        /// </summary>
        internal static string EDIT_ITEM {
            get {
                return ResourceManager.GetString("EDIT_ITEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is negative. Enter a more suitable number.
        /// </summary>
        internal static string ERROR_NEGATIVE {
            get {
                return ResourceManager.GetString("ERROR_NEGATIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is negative, or zero. Enter a more suitable number.
        /// </summary>
        internal static string ERROR_ZERO_NEG {
            get {
                return ResourceManager.GetString("ERROR_ZERO_NEG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press [ESC] at any time to return to previous Prompt or Menu.
        /// </summary>
        internal static string ESC_PROMPT {
            get {
                return ResourceManager.GetString("ESC_PROMPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;&lt;INVENTORY MENU&gt;&gt;.
        /// </summary>
        internal static string INV_MENU_TITLE {
            get {
                return ResourceManager.GetString("INV_MENU_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Selection.
        /// </summary>
        internal static string INVALID_SEL {
            get {
                return ResourceManager.GetString("INVALID_SEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;&lt;MAIN MENU&gt;&gt;.
        /// </summary>
        internal static string MAIN_MENU_TITLE {
            get {
                return ResourceManager.GetString("MAIN_MENU_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product name cannot be blank.
        /// </summary>
        internal static string NAME_EMPTY {
            get {
                return ResourceManager.GetString("NAME_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product NAME (MAX-26 chars).
        /// </summary>
        internal static string NAME_PROMPT {
            get {
                return ResourceManager.GetString("NAME_PROMPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to too long of a name (MAXLENGTH = 26).
        /// </summary>
        internal static string NAME_TOO_LONG {
            get {
                return ResourceManager.GetString("NAME_TOO_LONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is too large or contains alpha characters.
        /// </summary>
        internal static string PARSE_ERROR_DEC {
            get {
                return ResourceManager.GetString("PARSE_ERROR_DEC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is too large, contains alpha characters, or is not an integer.
        /// </summary>
        internal static string PARSE_ERROR_INT {
            get {
                return ResourceManager.GetString("PARSE_ERROR_INT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity of.
        /// </summary>
        internal static string QUANT_PROMPT {
            get {
                return ResourceManager.GetString("QUANT_PROMPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a numbered option from below.
        /// </summary>
        internal static string SELECT_OPTIONS {
            get {
                return ResourceManager.GetString("SELECT_OPTIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InventoryTracker v1.
        /// </summary>
        internal static string UI_VERSION {
            get {
                return ResourceManager.GetString("UI_VERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight (lb) of one unit of.
        /// </summary>
        internal static string WEIGHT_PROMPT {
            get {
                return ResourceManager.GetString("WEIGHT_PROMPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wholesale Price (USD) of one unit of.
        /// </summary>
        internal static string WHOLESALE_PROMPT {
            get {
                return ResourceManager.GetString("WHOLESALE_PROMPT", resourceCulture);
            }
        }
    }
}
